sonar.organization=ayushxod
sonar.projectKey=ayushxod_devsecops-project-one
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/terraform/**